---
name: playwright test across environments and tags
on:
  workflow_dispatch: 
jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: intall dependencies
        run: npm ci
      - name: install browsers
        run: npx playwright install --with-deps
      - name: run playwright test
        run: npx playwright test    
      - name: run playwright test from other repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          repository: anil2586-gif/learn-githubactions-sauce-demo
          event-type: my-event  
        
        
        
