---
name: playwright test across environments and tags
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: intall dependencies
        run: npm ci
      - name: install browsers
        run: npx playwright install --with-deps
      - name: run playwright test
        run: npx playwright test
  playwright-test:
    name: run playwright test from other repo
    needs: playwright
    uses: anil2586-gif/learn-githubactions-sauce-demo/.github/workflows/playwright-my.yml@main
