name: playwright test across environments and tags
on:
  push:
    branches: ['main','master']
  pull_request:
    branches: ['main', 'master']
  workflow_dispatch: 

jobs:
  playwright-matrix:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, qa, stage]
        tag: ["@smoke,"@regression"]
      
